name: 'Ponicode Squar'
description: 'Check if the files updated in the PR are well tested'
branding:
  icon: 'align-justify'  
  color: 'orange'
inputs: 
  repo_url:
    description: 'String: URL of the repo to be processed'
    required: true
  user_token:
    description: 'String: Ponicode SQUAR user token from Github Secrets'
    required: true
  impacted_files:
    description: 'String[]: List of the files updated in the PR'
    required: true
  branch:
    description: 'String: branch on which the PR applies'
    required: true
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo_url }}
    - ${{ inputs.user_token }}
    - ${{ inputs.impacted_files }}
    - ${{ inputs.branch }}